#include "ConfigStorage.h"
#include "model/FormKeyUtil.h"
#include "log.h"
#include <Windows.h>
#include <SimpleIni.h>
#include <filesystem>
#include <fstream>
#include <fmt/format.h>

// This file deliberately does NOT use the Win32 profile API (GetPrivateProfileString /
// WritePrivateProfileString). Under Mod Organizer 2 the INI lives on a virtualised path
// (Data\SKSE\Plugins\<Mod>\, redirected into the instance's `overwrite` folder), and the
// profile API's writes never reached disk there: every default registered cleanly
// according to the log, yet the file on disk kept nothing but its `[General]` header.
// Ordinary file I/O to the same path works (the header itself is written with ofstream),
// so all reads and writes go through SimpleIni, which the project already depends on.

namespace Config {

ConfigStorage* ConfigStorage::GetSingleton()
{
    static ConfigStorage instance;
    return &instance;
}

void ConfigStorage::Initialize(std::string_view modName)
{
    std::lock_guard<std::mutex> lock(m_mutex);

    if (m_initialized) {
        spdlog::warn("ConfigStorage: Already initialized as '{}', ignoring re-init as '{}'",
            m_modName, modName);
        return;
    }

    m_modName = modName;

    // Build path: Data\SKSE\Plugins\<ModName>\<ModName>_config.ini
    char pathBuffer[MAX_PATH];
    GetModuleFileNameA(nullptr, pathBuffer, MAX_PATH);
    std::string exePath(pathBuffer);
    std::string dataPath = exePath.substr(0, exePath.rfind('\\'));

    m_iniFolderPath = fmt::format("{}\\Data\\SKSE\\Plugins\\{}", dataPath, m_modName);
    m_iniPath = fmt::format("{}\\{}_config.ini", m_iniFolderPath, m_modName);

    spdlog::info("ConfigStorage: Initialized for '{}' at '{}'", m_modName, m_iniPath);
    m_initialized = true;
}

void ConfigStorage::EnsureIniFileExists()
{
    namespace fs = std::filesystem;

    // Create folder if needed
    if (!fs::exists(m_iniFolderPath)) {
        fs::create_directories(m_iniFolderPath);
        spdlog::info("ConfigStorage: Created directory '{}'", m_iniFolderPath);
    }

    // Create INI file with header if needed
    if (!fs::exists(m_iniPath)) {
        std::ofstream file(m_iniPath);
        if (file) {
            file << "; " << m_modName << " Configuration\n";
            file << "; Auto-generated by ConfigStorage\n\n";
            file << "[General]\n";
            file.close();
            spdlog::info("ConfigStorage: Created INI file '{}'", m_iniPath);
        } else {
            spdlog::error("ConfigStorage: Failed to create INI file '{}'", m_iniPath);
        }
    }
}

std::pair<std::string, std::string> ConfigStorage::ParseSectionKey(std::string_view qualifiedKey)
{
    size_t colonPos = qualifiedKey.find(':');
    if (colonPos != std::string_view::npos) {
        return {
            std::string(qualifiedKey.substr(0, colonPos)),
            std::string(qualifiedKey.substr(colonPos + 1))
        };
    }
    return { "General", std::string(qualifiedKey) };
}

namespace {

// Load the INI from disk. A missing file is not an error - callers treat an empty
// document the same way the profile API treated a missing file.
void LoadIni(CSimpleIniA& ini, const std::string& path)
{
    ini.SetUnicode();
    ini.SetMultiKey(false);
    ini.LoadFile(path.c_str());  // a missing file simply leaves `ini` empty
}

}  // namespace

std::string ConfigStorage::ReadIniString(const std::string& section, const std::string& key,
                                          const std::string& defaultValue)
{
    CSimpleIniA ini;
    LoadIni(ini, m_iniPath);
    const char* value = ini.GetValue(section.c_str(), key.c_str(), nullptr);
    return value ? std::string(value) : defaultValue;
}

void ConfigStorage::WriteIniString(const std::string& section, const std::string& key,
                                    const std::string& value)
{
    EnsureIniFileExists();

    // Read-modify-write: SimpleIni keeps the comment header and every other key, so
    // this stays equivalent to the single-key update the profile API used to do.
    CSimpleIniA ini;
    LoadIni(ini, m_iniPath);
    ini.SetValue(section.c_str(), key.c_str(), value.c_str());

    const SI_Error rc = ini.SaveFile(m_iniPath.c_str());
    if (rc < 0) {
        spdlog::error("ConfigStorage: Failed to write [{}]{} to '{}' (SI_Error {})",
            section, key, m_iniPath, static_cast<int>(rc));
    }
}

bool ConfigStorage::KeyExists(const std::string& section, const std::string& key)
{
    CSimpleIniA ini;
    LoadIni(ini, m_iniPath);
    return ini.GetValue(section.c_str(), key.c_str(), nullptr) != nullptr;
}

// Shared by GetInt and RegisterIntOption so both parse identically.
int ConfigStorage::ReadIniInt(const std::string& section, const std::string& key, int defaultValue)
{
    const std::string value = ReadIniString(section, key, std::string{});
    if (value.empty()) {
        return defaultValue;
    }
    try {
        return std::stoi(value);
    } catch (...) {
        spdlog::warn("ConfigStorage: [{}]{} = '{}' is not an integer, using {}",
            section, key, value, defaultValue);
        return defaultValue;
    }
}

// ========== Registration (C++ only) ==========

int ConfigStorage::RegisterIntOption(std::string_view key, int defaultValue)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    auto [section, keyName] = ParseSectionKey(key);

    // Store the default for Reset* to use later
    m_intDefaults[std::string(key)] = defaultValue;

    if (!KeyExists(section, keyName)) {
        WriteIniString(section, keyName, std::to_string(defaultValue));
        spdlog::info("ConfigStorage: Registered [{}]{} = {} (default)", section, keyName, defaultValue);
        return defaultValue;
    }

    // Key exists, return current value
    return ReadIniInt(section, keyName, defaultValue);
}

float ConfigStorage::RegisterFloatOption(std::string_view key, float defaultValue)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    auto [section, keyName] = ParseSectionKey(key);

    // Store the default for Reset* to use later
    m_floatDefaults[std::string(key)] = defaultValue;

    if (!KeyExists(section, keyName)) {
        WriteIniString(section, keyName, fmt::format("{:.6f}", defaultValue));
        spdlog::info("ConfigStorage: Registered [{}]{} = {:.6f} (default)", section, keyName, defaultValue);
        return defaultValue;
    }

    // Key exists, return current value
    std::string defStr = fmt::format("{:.6f}", defaultValue);
    std::string value = ReadIniString(section, keyName, defStr);
    try {
        return std::stof(value);
    } catch (...) {
        return defaultValue;
    }
}

std::string ConfigStorage::RegisterStringOption(std::string_view key, std::string_view defaultValue)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    auto [section, keyName] = ParseSectionKey(key);

    // Store the default for Reset* to use later
    m_stringDefaults[std::string(key)] = std::string(defaultValue);

    if (!KeyExists(section, keyName)) {
        WriteIniString(section, keyName, std::string(defaultValue));
        spdlog::info("ConfigStorage: Registered [{}]{} = '{}' (default)", section, keyName, defaultValue);
        return std::string(defaultValue);
    }

    // Key exists, return current value
    return ReadIniString(section, keyName, std::string(defaultValue));
}

// ========== Int ==========

int ConfigStorage::GetInt(std::string_view key, int defaultValue)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    auto [section, keyName] = ParseSectionKey(key);
    return ReadIniInt(section, keyName, defaultValue);
}

int ConfigStorage::SetInt(std::string_view key, int value)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    auto [section, keyName] = ParseSectionKey(key);
    WriteIniString(section, keyName, std::to_string(value));
    spdlog::trace("ConfigStorage: Set [{}]{} = {}", section, keyName, value);
    return value;
}

int ConfigStorage::ResetInt(std::string_view key, int defaultValue)
{
    // Use registered default if available, otherwise fall back to provided default
    int actualDefault = defaultValue;
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        auto it = m_intDefaults.find(std::string(key));
        if (it != m_intDefaults.end()) {
            actualDefault = it->second;
        }
    }
    return SetInt(key, actualDefault);
}

// ========== Float ==========

float ConfigStorage::GetFloat(std::string_view key, float defaultValue)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    auto [section, keyName] = ParseSectionKey(key);
    std::string defStr = fmt::format("{:.6f}", defaultValue);
    std::string value = ReadIniString(section, keyName, defStr);
    try {
        return std::stof(value);
    } catch (...) {
        return defaultValue;
    }
}

float ConfigStorage::SetFloat(std::string_view key, float value)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    auto [section, keyName] = ParseSectionKey(key);
    WriteIniString(section, keyName, fmt::format("{:.6f}", value));
    spdlog::trace("ConfigStorage: Set [{}]{} = {:.6f}", section, keyName, value);
    return value;
}

float ConfigStorage::ResetFloat(std::string_view key, float defaultValue)
{
    // Use registered default if available, otherwise fall back to provided default
    float actualDefault = defaultValue;
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        auto it = m_floatDefaults.find(std::string(key));
        if (it != m_floatDefaults.end()) {
            actualDefault = it->second;
        }
    }
    return SetFloat(key, actualDefault);
}

// ========== String ==========

std::string ConfigStorage::GetString(std::string_view key, std::string_view defaultValue)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    auto [section, keyName] = ParseSectionKey(key);
    return ReadIniString(section, keyName, std::string(defaultValue));
}

std::string ConfigStorage::SetString(std::string_view key, std::string_view value)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    auto [section, keyName] = ParseSectionKey(key);
    WriteIniString(section, keyName, std::string(value));
    spdlog::trace("ConfigStorage: Set [{}]{} = '{}'", section, keyName, value);
    return std::string(value);
}

std::string ConfigStorage::ResetString(std::string_view key, std::string_view defaultValue)
{
    // Use registered default if available, otherwise fall back to provided default
    std::string actualDefault(defaultValue);
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        auto it = m_stringDefaults.find(std::string(key));
        if (it != m_stringDefaults.end()) {
            actualDefault = it->second;
        }
    }
    return SetString(key, actualDefault);
}

// ========== Form ==========

RE::TESForm* ConfigStorage::GetForm(std::string_view key, RE::TESForm* defaultValue)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    auto [section, keyName] = ParseSectionKey(key);

    // Build default FormKey string
    std::string defaultFormKey = defaultValue
        ? SaveMigration::Model::FormKeyUtil::BuildFormKey(defaultValue)
        : "";

    std::string formKey = ReadIniString(section, keyName, defaultFormKey);
    if (formKey.empty()) {
        return defaultValue;
    }

    // Resolution goes through the VR-correct resolver, never a hand-built
    // runtime FormID fed to LookupByID.
    auto* form = SaveMigration::Model::FormKeyUtil::Resolve(formKey);
    if (!form) {
        spdlog::warn("ConfigStorage: Failed to resolve FormKey '{}' for [{}]{}",
            formKey, section, keyName);
        return defaultValue;
    }
    return form;
}

RE::TESForm* ConfigStorage::SetForm(std::string_view key, RE::TESForm* value)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    auto [section, keyName] = ParseSectionKey(key);

    std::string formKey = value ? SaveMigration::Model::FormKeyUtil::BuildFormKey(value) : "";
    WriteIniString(section, keyName, formKey);
    spdlog::trace("ConfigStorage: Set [{}]{} = '{}' (Form)", section, keyName, formKey);
    return value;
}

RE::TESForm* ConfigStorage::ResetForm(std::string_view key, RE::TESForm* defaultValue)
{
    return SetForm(key, defaultValue);
}

// ========== Select ==========

void ConfigStorage::RegisterSelectOptions(std::string_view key, const std::vector<std::string>& options,
                                           std::string_view defaultValue)
{
    std::lock_guard<std::mutex> lock(m_mutex);

    if (options.empty()) {
        spdlog::warn("ConfigStorage: Cannot register empty options list for '{}'", key);
        return;
    }

    m_selectOptions[std::string(key)] = options;

    // Determine the actual default: use provided defaultValue if valid, else first option
    std::string actualDefault;
    if (defaultValue.empty()) {
        actualDefault = options[0];
    } else {
        // Validate defaultValue is in options list
        bool found = false;
        for (const auto& opt : options) {
            if (opt == defaultValue) {
                found = true;
                break;
            }
        }
        if (found) {
            actualDefault = defaultValue;
        } else {
            spdlog::warn("ConfigStorage: Default '{}' not in options for '{}', using first option",
                defaultValue, key);
            actualDefault = options[0];
        }
    }

    // Store the default for ResetSelect to use later
    m_selectDefaults[std::string(key)] = actualDefault;

    // Write default to INI if key doesn't exist
    auto [section, keyName] = ParseSectionKey(key);
    if (!KeyExists(section, keyName)) {
        WriteIniString(section, keyName, actualDefault);
        spdlog::info("ConfigStorage: Registered select [{}]{} = '{}' (default, {} options)",
            section, keyName, actualDefault, options.size());
    } else {
        spdlog::info("ConfigStorage: Registered select [{}]{} ({} options, existing value kept)",
            section, keyName, options.size());
    }
}

std::string ConfigStorage::GetSelect(std::string_view key)
{
    std::lock_guard<std::mutex> lock(m_mutex);

    auto it = m_selectOptions.find(std::string(key));
    if (it == m_selectOptions.end() || it->second.empty()) {
        return "Option Not Found";
    }

    auto [section, keyName] = ParseSectionKey(key);
    std::string defaultOption = it->second[0];  // First option is default
    return ReadIniString(section, keyName, defaultOption);
}

std::string ConfigStorage::SetSelect(std::string_view key, std::string_view value)
{
    std::lock_guard<std::mutex> lock(m_mutex);

    // Validate against registered options
    auto it = m_selectOptions.find(std::string(key));
    if (it != m_selectOptions.end()) {
        bool valid = false;
        for (const auto& opt : it->second) {
            if (opt == value) {
                valid = true;
                break;
            }
        }
        if (!valid) {
            spdlog::warn("ConfigStorage: Invalid select value '{}' for key '{}', ignoring", value, key);
            // Return current value (need to read without lock, so unlock first)
            auto [section, keyName] = ParseSectionKey(key);
            std::string defaultOption = it->second.empty() ? "Option Not Found" : it->second[0];
            return ReadIniString(section, keyName, defaultOption);
        }
    }

    auto [section, keyName] = ParseSectionKey(key);
    WriteIniString(section, keyName, std::string(value));
    spdlog::trace("ConfigStorage: Set [{}]{} = '{}' (Select)", section, keyName, value);
    return std::string(value);
}

std::vector<std::string> ConfigStorage::GetSelectOptions(std::string_view key)
{
    std::lock_guard<std::mutex> lock(m_mutex);

    auto it = m_selectOptions.find(std::string(key));
    if (it != m_selectOptions.end()) {
        return it->second;
    }
    return { "Option Not Found" };
}

std::string ConfigStorage::ResetSelect(std::string_view key)
{
    std::lock_guard<std::mutex> lock(m_mutex);

    auto it = m_selectOptions.find(std::string(key));
    if (it == m_selectOptions.end() || it->second.empty()) {
        return "Option Not Found";
    }

    // Use stored default from RegisterSelectOptions, or fall back to first option
    std::string defaultOption;
    auto defIt = m_selectDefaults.find(std::string(key));
    if (defIt != m_selectDefaults.end()) {
        defaultOption = defIt->second;
    } else {
        defaultOption = it->second[0];  // Fallback to first option
    }

    auto [section, keyName] = ParseSectionKey(key);
    WriteIniString(section, keyName, defaultOption);
    return defaultOption;
}

// ========== Utility ==========

void ConfigStorage::FlushToDisk()
{
    // Nothing to flush: WriteIniString does a read-modify-write and calls SaveFile on
    // every set, so the file on disk is always current. Kept because it is part of the
    // public surface. (It previously called the profile-API cache flush - which was
    // never invoked from anywhere, and would not have helped regardless.)
}

void ConfigStorage::ReloadFromDisk()
{
    // Nothing to reload: every read opens the file, so external edits are picked up
    // on the next Get.
    spdlog::info("ConfigStorage: ReloadFromDisk (each read re-opens the file)");
}

} // namespace Config
